FROM python:3.13.2-slim
COPY --from=ghcr.io/astral-sh/uv:0.6.8 /uv /uvx /bin/

WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1
# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy
# ENV UV_SYSTEM_PYTHON=true

RUN apt-get update && \
    apt-get -y install gcc postgresql procps && \
    apt-get clean

COPY celery/start_worker.sh /start_worker.sh
RUN chmod +x /start_worker.sh

COPY celery/start_beat.sh /start_beat.sh
RUN chmod +x /start_beat.sh

COPY celery/start_flower.sh /start_flower.sh
RUN chmod +x /start_flower.sh

ADD . /app
RUN uv sync --frozen

# # Place executables in the environment at the front of the path
# ENV PATH="/app/.venv/bin:$PATH"

# Reset the entrypoint, don't invoke `uv`
ENTRYPOINT []

# Run the FastAPI application by default
# Uses `fastapi dev` to enable hot-reloading when the `watch` sync occurs
# Uses `--host 0.0.0.0` to allow access from outside the container
CMD ["uv", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]