# Generated by Django 5.1.5 on 2025-02-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
