# Generated by Django 5.0.7 on 2024-07-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('name', 'manufacturer')},
        ),
    ]
