name: CI

on:
  pull_request:
  workflow_dispatch:
    inputs:
      runnerLevel:
        description: "Runner log"
        required: true
        default: false
        type: boolean
      stepLevel:
        description: "Steps log"
        required: true
        default: false
        type: boolean

env:
  ACTIONS_RUNNER_DEBUG: ${{ inputs.runnerLevel && true || false }}
  ACTIONS_STEP_DEBUG: ${{ inputs.stepLevel && true || false }}
  UV_NO_SYNC: true
  # PATH: "/app/.venv/bin:$PATH"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run docker
        run: docker compose up -d --build
      - name: Analysing the code with ruff
        run: docker compose exec web ruff check
        if: always()
      - name: Analysing the code with mypy
        run: docker compose exec web mypy .
        if: always()
      - name: Check formating with djlint
        run: docker compose exec web djlint .
        if: always()
      - name: Check formating with black
        run: docker compose exec web ruff format --check
        if: always()
      - name: Run migrations
        run: docker compose exec web python manage.py migrate
        if: always()
      - name: Run tests
        run: docker compose exec web pytest
        if: always()
